
# Make sure we have our ENV_WEBSERVICE_DIR environment variable set.
if [ -z "$ENV_WEBSERVICE_DIR" ]; then
    echo "Need to set ENV_WEBSERVICE_DIR"
    exit 1
fi

COMPONENT=@COMPONENT@

WEBSERVICE_CONFIG_DIR=$ENV_WEBSERVICE_DIR/config
export WEBSERVICE_CONFIG_DIR

LOG4J_CONFIG_FILE_PROPERTY="-Dwebservice.log4j.file=$WEBSERVICE_CONFIG_DIR/log4j.xml"
COMPONENT_PROPERTY="-Dcomponent=$COMPONENT"
RUNTIME_PROPERTY="-Druntime.properties.dir=$WEBSERVICE_CONFIG_DIR"

export JAVA_OPTS="${LOG4J_CONFIG_FILE_PROPERTY} ${PID_PROPERTY} ${COMPONENT_PROPERTY} ${RUNTIME_PROPERTY}"