
# Make sure we have our ENV_ADDRESSBOOK_DIR environment variable set.
if [ -z "$ENV_ADDRESSBOOK_DIR" ]; then
    echo "Need to set ENV_ADDRESSBOOK_DIR"
    exit 1
fi

ADDRESSBOOK_CONFIG_DIR=$ENV_ADDRESSBOOK_DIR/config
export ADDRESSBOOK_CONFIG_DIR

LOG4J_CONFIG_FILE_PROPERTY="-Daddressbook.log4j.file=$ADDRESSBOOK_CONFIG_DIR/log4j.xml"
RUNTIME_PROPERTY="-Druntime.properties.dir=$ADDRESSBOOK_CONFIG_DIR"

export JAVA_OPTS="${LOG4J_CONFIG_FILE_PROPERTY} ${PID_PROPERTY} ${COMPONENT_PROPERTY} ${RUNTIME_PROPERTY}"
